# Generated by Django 4.2.9 on 2026-03-29 22:59

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Nome de usuário para login', max_length=50, unique=True, verbose_name='Login')),
                ('email', models.EmailField(help_text='Email será usado para login', max_length=254, unique=True, verbose_name='Email')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora de criação do usuário', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
                'ordering': ['-criado_em'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veterinario', models.CharField(help_text='Nome completo do veterinário', max_length=100, verbose_name='Nome do Veterinário')),
                ('email', models.EmailField(blank=True, help_text='Email de contato', max_length=100, null=True, verbose_name='Email')),
                ('celular', models.CharField(blank=True, help_text='Formato: (11) 99999-9999', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Formato: (11) 99999-9999', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')], verbose_name='Celular')),
                ('telefone', models.CharField(blank=True, help_text='Telefone fixo', max_length=16, null=True, verbose_name='Telefone')),
                ('logradouro', models.CharField(help_text='Rua, avenida, etc.', max_length=50, verbose_name='Logradouro')),
                ('numero_endereco', models.CharField(blank=True, help_text='Número da clínica/consultório', max_length=10, null=True, verbose_name='Número')),
                ('bairro', models.CharField(help_text='Bairro', max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(help_text='Cidade', max_length=50, verbose_name='Cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Unidade da Federação', max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, help_text='Formato: 00000-000', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Formato: 00000-000', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Veterinário',
                'verbose_name_plural': 'Veterinários',
                'db_table': 'veterinario',
                'ordering': ['veterinario'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.CharField(help_text='Nome completo do tutor', max_length=100, verbose_name='Nome do Tutor')),
                ('email', models.EmailField(help_text='Email de contato do tutor', max_length=100, verbose_name='Email')),
                ('celular', models.CharField(blank=True, help_text='Formato: (11) 99999-9999', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato: (11) 99999-9999', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')], verbose_name='Celular')),
                ('telefone', models.CharField(blank=True, help_text='Telefone fixo', max_length=20, null=True, verbose_name='Telefone')),
                ('logradouro', models.CharField(help_text='Rua, avenida, etc.', max_length=50, verbose_name='Logradouro')),
                ('numero_logradouro', models.CharField(blank=True, help_text='Número da residência', max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, help_text='Apartamento, casa, etc.', max_length=20, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(help_text='Bairro', max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(help_text='Cidade', max_length=50, verbose_name='Cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Unidade da Federação', max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, help_text='Formato: 00000-000', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Formato: 00000-000', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tutor', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'db_table': 'tutor',
                'ordering': ['tutor'],
                'indexes': [models.Index(fields=['tutor'], name='idx_tutor')],
            },
        ),
    ]
