# Generated by Django 4.2.9 on 2026-03-29 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(help_text='Nome da espécie (ex: Canina, Felina, Ave)', max_length=50, unique=True, verbose_name='Espécie')),
                ('ativo', models.BooleanField(default=True, help_text='Espécie ativa no sistema', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
                'db_table': 'especie',
                'ordering': ['especie'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(help_text='Nome do pet', max_length=50, verbose_name='Nome do Pet')),
                ('raca', models.CharField(blank=True, help_text='Raça do pet (opcional)', max_length=50, null=True, verbose_name='Raça')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], help_text='Sexo do pet', max_length=1, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento do pet', null=True, verbose_name='Data de Nascimento')),
                ('castrado', models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], help_text='Pet é castrado?', max_length=1, null=True, verbose_name='Castrado')),
                ('data_castracao', models.DateField(blank=True, help_text='Data da castração (se aplicável)', null=True, verbose_name='Data da Castração')),
                ('cor', models.CharField(blank=True, help_text='Cor predominante do pet', max_length=50, null=True, verbose_name='Cor')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso em quilogramas', max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('microchip', models.CharField(blank=True, help_text='Número do microchip', max_length=20, null=True, verbose_name='Microchip')),
                ('observacoes', models.TextField(blank=True, help_text='Observações gerais sobre o pet', null=True, verbose_name='Observações')),
                ('foto', models.ImageField(blank=True, help_text='Foto do pet', null=True, upload_to='pets/fotos/%Y/%m/', verbose_name='Foto')),
                ('ativo', models.BooleanField(default=True, help_text='Pet ativo no sistema', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pets.especie', verbose_name='Espécie')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.tutor', verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'db_table': 'pet',
                'ordering': ['pet'],
            },
        ),
        migrations.CreateModel(
            name='PetVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, help_text='Data de início do acompanhamento', verbose_name='Início do Acompanhamento')),
                ('ativo', models.BooleanField(default=True, help_text='Relacionamento ativo', verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o acompanhamento', null=True, verbose_name='Observações')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Pet')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veterinario', verbose_name='Veterinário')),
            ],
            options={
                'verbose_name': 'Pet-Veterinário',
                'verbose_name_plural': 'Pets-Veterinários',
                'db_table': 'pet_veterinario',
                'unique_together': {('pet', 'veterinario')},
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='veterinarios',
            field=models.ManyToManyField(related_name='pets', through='pets.PetVeterinario', to='core.veterinario', verbose_name='Veterinários'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['pet'], name='pet_idx'),
        ),
    ]
