# Generated by Django 4.2.9 on 2026-03-29 22:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloVacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_protocolo', models.CharField(help_text='Nome do protocolo de vacinação', max_length=100, verbose_name='Nome do Protocolo')),
                ('idade_inicial_dias', models.PositiveIntegerField(help_text='Idade mínima para começar o protocolo', verbose_name='Idade Inicial (dias)')),
                ('idade_final_dias', models.PositiveIntegerField(blank=True, help_text='Idade máxima para o protocolo (opcional)', null=True, verbose_name='Idade Final (dias)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolos', to='pets.especie', verbose_name='Espécie')),
            ],
            options={
                'verbose_name': 'Protocolo de Vacinação',
                'verbose_name_plural': 'Protocolos de Vacinação',
                'ordering': ['especie', 'idade_inicial_dias'],
            },
        ),
        migrations.CreateModel(
            name='ItemProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacina_nome', models.CharField(max_length=100, verbose_name='Nome da Vacina')),
                ('idade_aplicacao_dias', models.PositiveIntegerField(help_text='Idade em dias para aplicar esta vacina', verbose_name='Idade para Aplicação (dias)')),
                ('dose_numero', models.PositiveSmallIntegerField(default=1, verbose_name='Número da Dose')),
                ('intervalo_dias', models.PositiveIntegerField(blank=True, help_text='Dias até próxima dose/reforço', null=True, verbose_name='Intervalo para Próxima Dose')),
                ('obrigatoria', models.BooleanField(default=True, help_text='Vacina obrigatória no protocolo', verbose_name='Obrigatória')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vacinas.protocolovacinacao', verbose_name='Protocolo')),
            ],
            options={
                'verbose_name': 'Item do Protocolo',
                'verbose_name_plural': 'Itens do Protocolo',
                'ordering': ['protocolo', 'idade_aplicacao_dias', 'dose_numero'],
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacina', models.CharField(help_text='Nome ou tipo da vacina aplicada', max_length=100, verbose_name='Nome da Vacina')),
                ('tipo_vacina', models.CharField(blank=True, choices=[('V8', 'Óctupla (V8)'), ('V10', 'Déctupla (V10)'), ('V12', 'Dodectupla (V12)'), ('Antirrábica', 'Antirrábica'), ('Gripe_Canina', 'Gripe Canina'), ('Giardíase', 'Giardíase'), ('Leishmaniose', 'Leishmaniose'), ('Tríplice_Felina', 'Tríplice Felina'), ('Quádrupla_Felina', 'Quádrupla Felina'), ('FeLV', 'Leucemia Felina (FeLV)'), ('FIV', 'Imunodeficiência Felina (FIV)'), ('Outra', 'Outra')], help_text='Tipo padrão da vacina', max_length=20, null=True, verbose_name='Tipo de Vacina')),
                ('data_aplicacao', models.DateField(help_text='Data em que a vacina foi aplicada', verbose_name='Data de Aplicação')),
                ('observacao', models.TextField(blank=True, help_text='Observações sobre a aplicação da vacina', max_length=200, null=True, verbose_name='Observações')),
                ('lote', models.CharField(blank=True, help_text='Lote da vacina', max_length=50, null=True, verbose_name='Lote')),
                ('fabricante', models.CharField(blank=True, help_text='Fabricante da vacina', max_length=100, null=True, verbose_name='Fabricante')),
                ('validade', models.DateField(blank=True, help_text='Data de validade da vacina', null=True, verbose_name='Validade')),
                ('dose', models.PositiveSmallIntegerField(default=1, help_text='Número da dose (1ª, 2ª, 3ª, etc.)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dose')),
                ('doses_total', models.PositiveSmallIntegerField(blank=True, help_text='Número total de doses necessárias', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de Doses')),
                ('proxima_dose', models.DateField(blank=True, help_text='Data prevista para próxima dose/reforço', null=True, verbose_name='Próxima Dose')),
                ('intervalo_dias', models.PositiveIntegerField(blank=True, help_text='Intervalo em dias para próxima dose', null=True, verbose_name='Intervalo em Dias')),
                ('status', models.CharField(choices=[('Aplicada', 'Aplicada'), ('Agendada', 'Agendada'), ('Vencida', 'Vencida'), ('Cancelada', 'Cancelada')], default='Aplicada', help_text='Status da vacinação', max_length=10, verbose_name='Status')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor pago pela vacina', max_digits=8, null=True, verbose_name='Valor')),
                ('ativo', models.BooleanField(default=True, help_text='Vacina ativa no sistema', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='pets.pet', verbose_name='Pet')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacinas_aplicadas', to='core.veterinario', verbose_name='Veterinário')),
            ],
            options={
                'verbose_name': 'Vacina',
                'verbose_name_plural': 'Vacinas',
                'db_table': 'vacina',
                'ordering': ['-data_aplicacao'],
                'indexes': [models.Index(fields=['data_aplicacao'], name='vacina_data_idx'), models.Index(fields=['proxima_dose'], name='vacina_proxima_idx')],
            },
        ),
    ]
